### ISSUE TITLE
Disarming from Panel does not have correct status in home app

### ISSUE THREAD

**Issue by readylmay** [dustindclark/homebridge-envisalink#181]
Re: #158 

This is still occurring for me on 1.2.7. If the alarm is disarmed from panel, the correct state is not reflected in the home app. The spinner on the alarm panel will stay forever until I go into the status and set to off, which errors out with the below but puts the alarm in the right state. The error is expected as the alarm is set to off.

Steps to repro:
Set alarm to home with bypassed zones on home app
Disarm on panel
Home app spinner shows forever.

[08/12/```
2022, 11:41:43] [Envisalink] Failed setting panel state to 3 Error: Command 04011468 resulted in error from alarm: 023: API System Not Armed (sent in response to a disarm command)
    at EnvisalinkHomebridgePlatform.sendAlarmCommand (/usr/local/lib/node_modules/homebridge-envisalink/src/platform.ts:480:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at EnvisalinkPartitionAccessory.setPanelState (/usr/local/lib/node_modules/homebridge-envisalink/src/partitionAccessory.ts:199:13)
```

**Comment by readylmay** [comment]
anyone else seeing this behaviour, it looks similar to #200

**Comment by dkerr64** [comment]
After fixing #200, I noticed your issue and tried to reproduce but it is working for me.  I turned on zone bypass and armed from iPhone.  It goes into spinning state for duration of exit delay, then armed.  Then I went to panel and disarmed with my code.  It worked.

However, it turned up another unhandled alarm panel state (see my pull request #213) and that is:

```
"status": {
    "shortCode": "653",
    "longCode": "653",
    "description": "Partition Ready - Force Arming Enabled",
    "text": "readyforce",
    "action": "updatepartition",
    "verbSuffix": "is Ready and Force Arming is Enabled"
  }
```

Which is not handled.  With my pull request it is ignored and warning issued to log.  But it should be added to list of handled status values. @dustindclark I suggest handling the same way as "ready"... alarm goes to DISARMED state.  I could update my pull request to add it, or you can do it.

**Comment by dkerr64** [comment]
I added handling 'readyforce' to my PR #213

**Comment by readylmay** [comment]
@dkerr64 this is not fixed in 1.2.10 beta. 

Steps to reproduce:
1. arm alarm at panel or in home app with zones bypassed. 
2. disarm at panel
3. recieve notification (push notification banner) that alarm is disarmed
4. Home App alarm tile stuck in "Arming..." with spinner loop. 

If I disarm through the home app, the status is correct and does not go to arming spinner.

**Comment by dkerr64** [comment]
Between steps 1 and 2 do you wait for the exit delay period to pass (ie, alarm actually enters armed state) or disarm before then?

Step 4, is this the same whether you arm from panel or arm from app?

**Comment by readylmay** [comment]
1. Yes, the exit delay completes and the armed status is correct in Home app. 

2. From App - if I disarm from App, the Alarm goes to the correct status of "Off" immediately.

**Comment by dkerr64** [comment]
I believe that I am able to reproduce this problem.  The Apple Home icon changes to disarmed / off state but there is still a spinning icon.  If you open up the apple home icon then I see the "Arming..." like you describe.

If I then close the zone that was bypassed, then the "Arming..." stops and all is well.

I have traced the message flow from envisalink into the plugin and I think the bug is [here](https://github.com/dustindclark/homebridge-envisalink/blob/b10d93963aeaf5914f413bd72070c8aedb6dac24/src/partitionAccessory.ts#L135) where the alarm current state is set to DISARMED, but the alarm target state is left unchanged.... the previously set target state was to an ARM state.  I think we need to add
`targetState = this.platform.Characteristic.SecuritySystemTargetState.DISARM;`
just like it is set when handling the ready message (which is what is sent when I close the bypassed zone).

David

**Comment by dkerr64** [comment]
@dustindclark could you merge #252 and tag another beta please so we can see if this fixes @readylmay problem.

Thanks
David
