### ISSUE TITLE
Envisalink Stopped Working (See Attached Logs)

### ISSUE THREAD

**Issue by erfind** [dustindclark/homebridge-envisalink#19]
I'm unsure of what is broken here...everything was working and then just stopped. I did update everything with sudo apt-get update and sudo npm -g update. All plugins are installed as 

sudo npm -g install homebridge-envisalink

and I have never had a problem recognising these before...

Jul 26 19:30:27 HomeHomebridge homebridge[4884]: [7/26/2017, 7:30:27 PM] ERROR LOADING PLUGIN homebridge-envisalink:
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: [7/26/2017, 7:30:27 PM] Error: Cannot find module 'nodealarmproxy/index.js'
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Function.Module._resolveFilename (module.js:469:15)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Function.Module._load (module.js:417:25)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Module.require (module.js:497:17)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at require (internal/module.js:20:19)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Object.<anonymous> (/usr/lib/node_modules/homebridge-envisalink/index.js:2:11)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Module._compile (module.js:570:32)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Object.Module._extensions..js (module.js:579:10)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Module.load (module.js:487:32)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at tryModuleLoad (module.js:446:12)
Jul 26 19:30:27 HomeHomebridge homebridge[4884]: at Function.Module._load (module.js:438:3)

-----

Jul 26 19:30:30 HomeHomebridge homebridge[4884]: throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: ^
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: Error: The requested platform 'Envisalink' was not registered by any plugin.
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at API.platform (/usr/lib/node_modules/homebridge/lib/api.js:122:13)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:284:45)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Module._compile (module.js:570:32)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Object.Module._extensions..js (module.js:579:10)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Module.load (module.js:487:32)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at tryModuleLoad (module.js:446:12)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Function.Module._load (module.js:438:3)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at Module.runMain (module.js:604:10)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at run (bootstrap_node.js:389:7)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at startup (bootstrap_node.js:149:9)
Jul 26 19:30:30 HomeHomebridge homebridge[4884]: at bootstrap_node.js:504:3

Any ideas?

**Comment by erfind** [comment]
I located the problem. In the index.js file for envisalink we need to change the 

var nap = reqiure('index.js');

to reflect a change made in the nodealarmproxy which removed the index.js file and instead references the nodealarmproxy.js file instead.

var nap = require('nodealarmproxy/nodealarmproxy.js');

I am unsure about how to submit the change request otherwise I would send it in myself :)

**Comment by erfind** [comment]
Okay, the plugin is able to load with that change. But now anytime it runs it causes everything attached to homebridge to go into the “Not Responding” state. Any ideas?

**Comment by erfind** [comment]
I also noticed on my Envisalink device, that it was recently updated. Could something have changed that is causing this error? And is anyone else having trouble besides me?

**Comment by erfind** [comment]
@dustindclark any ideas on this one? I have had to remove the Envisalink from my HomeKit which sucks a little as this plugin has been an awesome way to manage setting and disarming with multiple people in our home.

**Comment by dstapleton92** [comment]
Hey I see this issue is still open. I recently got into homebridge and I tried this out for my DSC system with an Envisalink card. As mentioned above, I did have to change the require statement because nodealarmproxy eliminated index.js. Once I did that, I noticed the issue where everything was stuck “updating” in the Home app. After much troubleshooting, I was able to track down the problem:

Things hang up when the ready and alarm states of the partition are queried. There are no issues getting the sensor states, but they get stuck updating because of the partition status query failure. I’ve traced this to a breaking change in nodealarmproxy, specifically a change in behavior to getCurrent. It no longer accepts a callback function as an argument, and instead causes the ‘data’ event to be emitted. Because of this, program flow hangs because the hap callback is never invoked with the partition status. 

I played around with a fix, but couldn’t find an elegant solution that wasn’t buggy. It’s difficult because the alarm state and ready state are queried separately by HAP, and each of these must call getCurrent(), which triggers an event listener elsewhere in code with no direct access to the hap callback in order to send the data back. I played around with setting the hap callbacks as global variables, which worked, but it was very messy and seemed laggy. 

Unfortunately I don’t have time to come up with a fix for this at the moment. I just wanted to share this information in hopes that it could be useful to someone else. In the meantime, I installed the previous version of homebridge-envisalink (which uses the previous version of nodealarmproxy) and it is working perfectly and is very responsive.

**Comment by SirNoble** [comment]
@dstapleton92 Hi, purchased a Envisalink 4 in home it will work with Homekit. 
Which version would I need to install to get it working? 0.1.6?

Will be using it for a DSC security system.

Also have another question, and sorry for hijacking this page. 
But, when armed from the pin pad, does this get reflected on the Homekit app?

Does it come under security in Homekit?
![untitled](https://user-images.githubusercontent.com/31987189/31422130-8305c33e-ae97-11e7-94d9-68e6284211af.png)

**Comment by ToddGreenfield** [comment]
@dstapleton92 yes, install 0.1.6. The current version had issues due to a dependency. Changes on the alarm system panel should be reflected in HomeKit.

**Comment by dstapleton92** [comment]
@SirNoble @ToddGreenfield is correct. 0.1.6 of this plugin works correctly. Arming/disarming your alarm from the keypad will reflect in the Home app, triggering a notification on your iOS devices almost instantly (you can turn this off, or do what I did and set it to only send notifications when you are not home). 

I actually found a fork of this repo that has been updated to use the latest nodealarmproxy version. Additionally, some new features were added, such as user programs (PGM). I installed it and it’s been working great. [https://github.com/mattvj/homebridge-envisalink](https://github.com/mattvj/homebridge-envisalink)

**Comment by dstapleton92** [comment]
@SirNoble Your alarm partition will be shown as a home security device, and all of your zones will show up as individual sensors in the Home app (you can disable this by setting suppressZoneAccessories to true in the config). This is neat because you can use your motion detectors or your door contact sensors in automations to trigger scenes or other accessory actions. 

One thing I’ve noticed is that Siri will not control the alarm. I’m always told I need to open the Home app. Not sure if that is a security thing. I know for my garage door, Siri can control it I just have to unlock my iPhone first.

**Comment by SirNoble** [comment]
@dstapleton92 
How do you install Mattvj version of the Homebridge plugin?
I know you mentioned PGM, anything else interesting for an average user. 


Also, for each motion sensor do you need do a zone for each? 
I have 6 motion sensors for each room, how does it know which is which motion sensor for each room in the Home app?

**Comment by dustindclark** [comment]
Hey guys…sorry for the lack of activity on this.  I haven’t had much time to devote to this plugin recently.  If anyone wants to submit a PR with a fix (even if that’s just reverting version upgrades), I would be glad to merge and publish.  Thanks.
