### ISSUE TITLE
Time and date

### ISSUE THREAD

**Issue by ghost** [dustindclark/homebridge-envisalink#25]
Is there a way to change the time zone? I love that it auto sets but it’s 3 hours fasts for me. 

Thanks!

**Comment by dstapleton92** [comment]
@robini629 There was a bug affecting the date that was fixed in the most recent version. Make sure you’re running the latest version. Regarding the time, it should be using the time of your system running homebridge (raspberry pi, etc). Can you confirm that your system is set to the correct time zone / locale?

**Comment by dustindclark** [comment]
Just published 0.2.2.  This should be resolved.  Please try updating.
