### ISSUE TITLE
What is the purpose of the off switch?

### ISSUE THREAD

**Issue by carson-autocicd** [dustindclark/homebridge-envisalink#269]
I’m not sure when this was added but my alarm has the typical Off Night Home Away selections and then a huge on / off switch next to that. What’s the purpose of the on / off switch (presently the selector is set to off and the large on off switch is set to on). Thanks - your app is fantastic!

**Comment by dustindclark** [comment]
Depends on your config. There's an iOS bug that doesn't show the proper label on each switch, but it's likely the bypass switch. If on, open zones will be bypassed while arming.

**Comment by dustindclark** [comment]
Closing for now. Feel free to reopen if you have more questions

**Comment by brownjd** [comment]
I get two switches. Neither seems to do anything. I would rather suppress them if possible.

**Comment by dustindclark** [comment]
One likely enables/disables Chime, and one likely enables/disables auto-bypass. See readme for details on what these do. 

That said, I've finally found a hack in iOS 17 that allows you to identify them. Tap on your alarm in the Home app, then tap on the Settings Gear > Accessories. Tap on each switch (not the switch itself, but to the right of that). Then tap the Settings gear on that switch. Clear the name here, and the underlying (real) name will appear grayed out in the background. You should be able to name it something sensible here as well.

**Comment by brownjd** [comment]
That works in IOS 16.6.1 as well. They still don't seem to do anything though. I've tried turning the chime switch on and off and it doesn't turn the door chime on or off. I had to use *4 to enable and disable from the panel.

**Comment by dustindclark** [comment]
Do you have a DSC or Honeywell panel?

**Comment by brownjd** [comment]
DSC

**Comment by dustindclark** [comment]
`*4` is the command being used (see code [here](https://github.com/dustindclark/homebridge-envisalink/blob/master/src/partitionAccessory.ts#L79)). Perhaps you have it enabled on the incorrect partition? Or perhaps it's really the bypass switch. What does the default name show as?

**Comment by brownjd** [comment]
Main House Chime

**Comment by dustindclark** [comment]
Any Homebridge logs when you toggle the switch? I actually have my Chime automated such that it turns off at 11PM and turns on at 7AM...have not had any issues with that.

**Comment by brownjd** [comment]
Edit, never mind. It works, now. I edited the config and it started working.

**Comment by dustindclark** [comment]
Looks like it's trying to set this on the pool house partition instead of the main house. Can you share your config and remove the password?DustinSent from my iPhoneOn Sep 15, 2023, at 17:32, brownjd ***@***.***> wrote:﻿
[9/15/2023, 5:30:26 PM] [Envisalink] Setting accessory details for partition: {
"name": "Pool House",
"number": 2,
"enableChimeSwitch": true,
"chimeCommand": "0712*4",
"chimeActive": true,
"pin": "XXXX",
"status": {
"shortCode": "650",
"longCode": "650",
"description": "Partition Ready",
"text": "ready",
"action": "updatepartition",
"verbSuffix": "Ready"
},
"bypassEnabled": false
}
[9/15/2023, 5:30:26 PM] [Envisalink] Partition 2: ready, mode: undefined.
[9/15/2023, 5:30:26 PM] [Envisalink] Setting current state to 3
[9/15/2023, 5:30:26 PM] [Envisalink] Setting target state to 3
[9/15/2023, 5:30:26 PM] [Envisalink] Pool House Ready
