### ISSUE TITLE
Unable to Install Plugin, Ideas?

### ISSUE THREAD

**Issue by erfind** [dustindclark/homebridge-envisalink#28]
![615c2f56-6715-473c-a6d3-122802ee11f2](https://user-images.githubusercontent.com/11017553/33277191-64fa9c44-d35d-11e7-9b75-ac82fc568369.png)

**Comment by BigDogJonx** [comment]
Im having the same issue, cant seem to get it to update either.  Ended up having to go back to 0.1.6.

**Comment by BigDogJonx** [comment]
I suspect like @erfind that because we are running these on Raspberry Pi's, that the install script has an issue.  It references trying to copy the git clone to /root/.npm when it should be /home/pi/.npm for Raspberry Pi.  Not sure where I can correct this.  Im not much of an expert on the scripts or how to change it and then run it.  I cant seem to find where its getting this from since I didnt see it on the package.json or index file itself.

**Comment by ToddGreenfield** [comment]
Can you install any plugin successfully? Do You normally use sudo to install plugins:?

**Comment by BigDogJonx** [comment]
Yes I have no problem installing other plugsins, as a matter of fact I have no issue installing 0.1.6 when I did awhile back.  Yes on Raspberry Pi we have to use sudo.

Just tried to cheat it by creating a symbolic link of /root pointing to /home/pi and that didnt work, still giving permission denied (even though the /root has 777 permissions).

**Comment by dustindclark** [comment]
I initially had this problem installing as well but don't remember what the fix was.  It was permissions related though.  It has to do with the NodeAlarmProxy dependency:

`"nodealarmproxy": "git://github.com/mattvj/NodeAlarmProxy.git",`

As soon as the latest version on NodeAlarmProxy is published to npm, I can reference it there instead of from GitHub.  I have reached out to @mattvj but have not heard back.

**Comment by dustindclark** [comment]
Sorry...I missed that the NodeAlarmProxy dependency was a fork.  I'll try to submit a pull request to the main repo this evening.

**Comment by ToddGreenfield** [comment]
One exists already, maybe a friendly nudge again... The install should still work using a git repo though... I run on RPI and do not use sudo to install packages, but re-tested and it worked ok. I also ran with sudo and it installed fine.

**Comment by ToddGreenfield** [comment]
I use option 2 from this doc to not have to use sudo - https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by dustindclark** [comment]
I was able to merge the PR.  Didn't realized that I was granted collaborator access from a previous contribution.  I've requested an npm publish from the repo owner.

**Comment by BigDogJonx** [comment]
@ToddGreenfield  Thanks, I updated the npm permissions as well, used option1 on that doc.  Some update may have changed this, because now that I recall, I remember not having to use sudo before about 6-8mo ago when I setup the whole homebridge on my RPi.  Thanks again.

**Comment by BigDogJonx** [comment]
@dustindclark I believe this issue should be closed.  I was able to install the 0.2.2 finally using the command  `npm install -g homebridge-envisalink@0.2.2` with no errors like the /root directory creation issue.

**Comment by dustindclark** [comment]
Thanks @BigDogJonx .  Nodealarmproxy has been published upstream, so I will close this issue once I'm referencing the npm version rather than the source.
