### ISSUE TITLE
Help getting Config.json to be accepted

### ISSUE THREAD

**Issue by amanofcharacter** [dustindclark/homebridge-envisalink#33]
Hi, I'm totally new to homebridge. I got my Raspberry Pi 2 running raspbian to successfully run homebridge and be recognized by my iPhone. I went to start configuring the config.json file for the envisalink, and I can't seem to get it to work. JSONLint tells me that my config file is valid, but home bridge keeps giving the following error:

[2018-2-8 20:09:00] No plugins found. See the README for information on installing plugins.
[2018-2-8 20:09:00] There was a problem reading your config.json file.
[2018-2-8 20:09:00] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-2-8 20:09:00]
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 11
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

Here is my config.json. I compiled this as an amalgamation of varius examples that I found while researching the envisalink plugin. There could be something totally wrong with this and I'd never know it. I have no idea if my formatting is off or what:

{
	"bridge": {
		"name": "Homebridge",
		"username": "MY RAS PI MAC ADDRESS",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "Envisalink",
		"host": "MY ENVISALINK LOCAL IP",
		"deviceType": "DSC",
		"password": "MY ENVISALINK LOCAL HTTP PASSWORD",
		"pin": "MY ALARM KEYPAD PIN",
		"suppressZoneAccessories": false,
		"suppressClockReset": false,
		"partitions": [{
			"name": "Alarm"
		}],
		"zones": [{
				"name": "1 Front Door",
				"type": "door",
				"partition": 1
			},
			{
				"name": "2 Kitchen Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "3 Dining Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "4 Dining Door",
				"type": "door",
				"partition": 1
			},
			{
				"name": "5 Office Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "6 Bathroom Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "7 Theater Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "8 Master Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "10 Living Room Window",
				"type": "window",
				"partition": 1
			},
			{
				"name": "11 Hall Motion",
				"type": "motion",
				"partition": 1
			}
		]
	}]
}

Can anyone help me? Does it look like I've typed anything incorrectly? I'm using Atom to edit the text, and then copying it all into the Putty SSH application, while editing the config.json. Thanks for any help!

P.S. Not sure if this matters, but I believe I have a second partition on this alarm panel, since the house is divided. The other side is unoccupied and I don't believe there are any active zones/leads going to the panel. I do have a zone skipped. The list above starts with Zone 1 and goes down to the Hall Motion, which is Zone 11. Zone 9 is skipped. Not sure if I have to account for that.

**Comment by IMNotMax** [comment]
I found some differencies in your config.json in the platform definition. 

Hope this helps

Here mine :

   {
                        "platform": "Envisalink",
                        "host": "192.168.0.000",
                        "deviceType": "DSC",
                        "password": "UserDSC",
                        "pin": "0000",
                        "suppressZoneAccessories": false,
                        "partitions": [ ....

**Comment by JustinDavidMartin** [comment]
Thanks for looking at it for me. I'm wondering if you could tell me specifically what is different? The only difference I see is that my config had the line:

"suppressClockReset": false,

I tried deleting this line and saving the adjustment, but I still got the same error.

**Comment by JustinDavidMartin** [comment]
Well I found part of my problem. I hadn't actually installed the envisalink plugin. I got it installed, but I'm still getting an error that there's something wrong with my config.json file. Any help is appreciated.

**Comment by IMNotMax** [comment]
Of course... install a plugin before adding a config to the config file :)

What is the error you have ?

**Comment by JustinDavidMartin** [comment]
Since installing the plugin, I no longer get the "no plugins" error, but I still get an error regarding my config.json:

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2018-2-9 07:29:28] Loaded plugin: homebridge-envisalink
[2018-2-9 07:29:28] Registering platform 'homebridge-envisalink.Envisalink'
[2018-2-9 07:29:28] ---
[2018-2-9 07:29:28] There was a problem reading your config.json file.
[2018-2-9 07:29:28] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2018-2-9 07:29:28]
/usr/local/lib/node_modules/homebridge/lib/server.js:207
    throw err;
    ^

SyntaxError: Unexpected token : in JSON at position 11
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/local/lib/node_modules/homebridge/lib/server.js:201:19)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)

I've also update my config file a bit, I'll post it here:

{
	"bridge": {
		"name": "Homebridge",
		"username": "74:DA:38:59:FF:B2",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "Envisalink",
		"host": "--- My IP ---",
		"deviceType": "DSC",
		"password": "---******---",
		"pin": "---***---",
		"suppressZoneAccessories": false,
		"suppressClockReset": false,
		"partitions": [{
			"name": "Alarm"
		}],
		"zones": [{
				"name": "Front Door",
				"type": "door",
				"partition": 1,
				"zoneNumber": 1
			},
			{
				"name": "Kitchen Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 2
			},
			{
				"name": "Dining Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 3
			},
			{
				"name": "Dining Door",
				"type": "door",
				"partition": 1,
				"zoneNumber": 4
			},
			{
				"name": "Office Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 5
			},
			{
				"name": "Bathroom Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 6
			},
			{
				"name": "Theater Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 7
			},
			{
				"name": "Master Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 8
			},
			{
				"name": "Living Room Window",
				"type": "window",
				"partition": 1,
				"zoneNumber": 10
			},
			{
				"name": "Hall Motion",
				"type": "motion",
				"partition": 1,
				"zoneNumber": 11
			}
		]
	}]
}

The differences from last time are that I added the "zoneNumber" fields to account for the skipped zone I have on my alarm system. Above, I have my host IP, password, and PIN blanked out just when I'm pasting them here. In my actual file, I've got my Envisalink local IP address, the web UI 6 digit password, and the 4 digit alarm keypad PIN.

One main question I have is the portion at the very top of the config, the "bridge" section. I've entered the MAC address of my Raspberry Pi in the "username" field, and I just left the port as the one that is entered in the example config.json that I found somewhere. I don't remember where. Are these fields correct? Should the "username" and "port" be something else? How would I know what to enter.

The JSONLint.com site still says my config is valid.

**Comment by IMNotMax** [comment]
Username is a fictive MAC address. Using a MAC address from your network should create a conflict !

**Comment by JustinDavidMartin** [comment]
So it's fictive as in it doesn't really matter what it is, at all?

**Comment by JustinDavidMartin** [comment]
So I think I was not editing the config.json correctly. I kept typing "nano config.json" while not in the "/.homebridge" directory. When I edited the config from that directory, everything seemed to click and Homebridge started successfully.

The alarm leads were all added and giving a status. Now I'm just running into a problem where Hombridge crashed when I attempt to arm or disarm. I get the following error:

[2018-2-9 08:37:08] Homebridge is running on port 51826.
server bound
actual connected
[2018-2-9 08:37:13] [Envisalink] Setting the current time on the alarm system to: 0837020918
sendcommand 010083702091897
actual disconnected
[2018-2-9 08:41:40] [Envisalink] Attempting to set alarm state to:  0
[2018-2-9 08:41:40] [Envisalink] Arming alarm to Stay/Night.
sendcommand 0311C5
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: This socket has been ended by the other party
    at Socket.writeAfterFIN [as write] (net.js:356:12)
    at sendcommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:253:12)
    at Object.exports.manualCommand (/usr/local/lib/node_modules/homebridge-envisalink/node_modules/nodealarmproxy/nodealarmproxy.js:263:3)
    at EnvisalinkAccessory.processAlarmState (/usr/local/lib/node_modules/homebridge-envisalink/index.js:433:17)
    at EnvisalinkAccessory.processDelayedEvents (/usr/local/lib/node_modules/homebridge-envisalink/index.js:521:18)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
pi@raspberrypi:~/.homebridge $
