### ISSUE TITLE
Getting Randomly Notifications of System's Arm status

### ISSUE THREAD

**Issue by peros550** [dustindclark/homebridge-envisalink#43]
I'm getting randomly notifications that my Alarm system was just armed, when nobody touched the Alarm system. In fact, the alarm system may be in Armed state for days. 

Anybody else having the same issue?

**Comment by dustindclark** [comment]
This is likely the result of a problematic plugin restarting homekit.  Check your homekit logs to find the root cause, because I'm unable to recreate.  You can also turn off notifications for your panel if you are so incline using the Home app.  Feel free to reopen if you determine that this is an issue with this plugin.
